# https://doc.rust-lang.org/cargo/reference/config.html
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[env]
GETTEXT_SYSTEM = "1"

[build]
rustflags = ["--cfg", "tokio_unstable"]

