// Buildjob properties
properties([
  buildDiscarder(
    logRotator(
      artifactDaysToKeepStr: "31",  // Keep artifacts for max 31 days
      artifactNumToKeepStr: "5",    // Keep artifacts for last 5 builds
      daysToKeepStr: "90",          // Keep build info for 90 days
      numToKeepStr: "60"            // Keep a max of 60 builds
    )
  )
])

pipeline {
    agent { node { label 'docker' } }
    options {
        timestamps()
        parallelsAlwaysFailFast()
        timeout(time: 2, unit: "HOURS")
        disableConcurrentBuilds(abortPrevious: env.BRANCH_NAME != "master")
    }
    stages {
        stage("Sanity") {
            agent {
                dockerfile { 
                    filename "Dockerfile"
                    dir "scripts/jenkins"
                    label "docker"
                    additionalBuildArgs "-t opensesame"
                }
            }
            steps {
                sh "cargo fmt --check"
            }
        }
        stage("Test") {
            parallel {
                stage('clippy') {
                    agent {
                        dockerfile {
                            filename "Dockerfile"
                            dir "scripts/jenkins"
                            label "docker"
                            additionalBuildArgs "-t opensesame"
                        }
                    }
                    steps {
                        script {
                            sh "cargo clippy"
                        }
                    }
                }
                stage('cargo test') {
                    agent {
                        dockerfile {
                            filename "Dockerfile"
                            dir "scripts/jenkins"
                            label "docker"
                            additionalBuildArgs "-t opensesame"
                        }
                    }
                    steps {
                        script {
                            sh "cd debian && ./postrm"
                            sh "cd debian && ./postinst"
                            sh "cargo test"
                        }
                    }
                }
            }
        }
        stage("Build") {
            agent {
                dockerfile { 
                    filename "Dockerfile_cross"
                    dir "scripts/jenkins"
                    label "docker"
                    additionalBuildArgs "-t opensesame_cross"
                }
            }
            steps {
                sh "cargo deb --target=armv7-unknown-linux-gnueabihf"
                archiveArtifacts artifacts: "target/armv7-unknown-linux-gnueabihf/debian/*.deb", fingerprint: false
            }
        }
    }
}
